apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.containerPort }}
  selector:
    run: {{ .Release.Name }}

